"""
Parallax — UX Report Data Model
Aggregated report from all persona journeys.
"""

from pydantic import BaseModel, Field
from typing import Optional
from datetime import datetime

from .finding import UXFinding
from .journey import Journey


class PersonaSummary(BaseModel):
    """Summary of a single persona's experience."""
    persona_name: str
    persona_age: int
    task_completed: bool
    total_steps: int
    max_frustration: int
    gave_up: bool
    gave_up_reason: Optional[str] = None
    key_confusions: list[str] = Field(default_factory=list)
    overall_difficulty: Optional[str] = None


class UXReport(BaseModel):
    """Complete UX testing report aggregating all persona journeys."""
    report_id: str
    target_url: str
    task: str
    
    # Timing
    created_at: str = Field(default_factory=lambda: datetime.utcnow().isoformat())
    
    # Persona results
    persona_summaries: list[PersonaSummary] = Field(default_factory=list)
    journeys: list[Journey] = Field(default_factory=list)
    
    # Aggregated findings
    findings: list[UXFinding] = Field(default_factory=list)
    
    # High-level stats
    task_completion_rate: float = 0.0
    average_frustration: float = 0.0
    average_steps: float = 0.0
    personas_who_gave_up: list[str] = Field(default_factory=list)
    
    # Executive summary (generated by Analyst Agent)
    executive_summary: Optional[str] = None
    top_recommendations: list[str] = Field(default_factory=list)
    
    def calculate_stats(self):
        """Calculate aggregate statistics from persona summaries."""
        if not self.persona_summaries:
            return
        
        n = len(self.persona_summaries)
        completed = sum(1 for p in self.persona_summaries if p.task_completed)
        self.task_completion_rate = round(completed / n * 100, 1)
        self.average_frustration = round(
            sum(p.max_frustration for p in self.persona_summaries) / n, 1
        )
        self.average_steps = round(
            sum(p.total_steps for p in self.persona_summaries) / n, 1
        )
        self.personas_who_gave_up = [
            p.persona_name for p in self.persona_summaries if p.gave_up
        ]
